### ISSUE TITLE
Unable to use PIN auth model for tokenization

### ISSUE THREAD

**Issue by gboyegadada** [Flutterwave/flutterwave-php#48]
I am unable to do "tokenization" with the PIN auth model. When I looked in the Card source code and noticed it is hardcoded to take a $bvn argument even if I am opting to use PIN auth model.

**Comment by gondylife** [comment]
Hello,

You can't tokenize with the PIN auth model, it is either NOAUTH or BVN.
What is your use case for tokenization?

Regards

**Comment by gboyegadada** [comment]
I need user to be able to enter card details the normal way with card number + pin + cvv + otp and not have to ask for his/her bvn (sorry I am using your api for the first time)

**Comment by gondylife** [comment]
Alright, 

You don't need to tokenize, use the charge method, and you can use the PIN auth model for Mastercards cards and Verve Cards, but you need to use VBVSECURECODE auth model for Visa Cards.

Regards

**Comment by gboyegadada** [comment]
Ok, thanks.
